BP-234 diagram events over time
bptlab/argos-frontend pull request #10
Opened 2017-02-28 15:39 UTC by julianweise

Medium refactorings were necessary in ProductView to met new requirements of dataloading/architecture.
Please see commit messages for more details.

2017-02-28 15:40 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-03-02 07:48 UTC, friedow requested changes

2017-03-02 07:48 UTC, friedow commented on src/ProductView/Diagram/LineChart.js
> +        datePartsA = datePartsA.split("-");
Assigning an array to a string variable makes it harder to read. I suggest using a new const instead.

2017-03-02 07:48 UTC, friedow commented on src/ProductView/Diagram/LineChart.js
> +            dataset.push(this.buildChartDataset(eventDataContainer.eventType, eventDataContainer.events));
Please extract the return value of buildChartDataset to a new variable.

2017-03-02 07:48 UTC, friedow commented on src/ProductView/Diagram/LineChart.js
> +                x: event[timeStampAttribute].split("T")[0],
The exact same splitting was used in LineChart > sortEventsByTime in line 9. Please extract it to a method.

2017-03-02 07:48 UTC, friedow commented on src/ProductView/Diagram/LineChart.js
> +            backgroundColor: "rgba(0, 78, 100, 0.5)",
Extract this to config?

2017-03-02 07:48 UTC, friedow commented on src/ProductView/Diagram/LineChart.js
> +            const chart = new Chart(chartContext, {
Extract chart config object to variable.

2017-03-02 07:48 UTC, friedow commented on src/ProductView/ProductView.js
> +            eventData: [
No newline here

2017-03-02 07:48 UTC, friedow commented on src/ProductView/ProductView.js
> +        const eventContainer = this.state.eventData.find((eventContainer) => {
The exact same comparison was used in LineChart > handleEventData in line 37. Please extract it to a method.

2017-03-02 07:48 UTC, friedow commented on src/ProductView/ProductView.js
> +                    <LineChart
No newline here.

2017-03-02 07:48 UTC, friedow commented on src/ProductView/Diagram/LineChart.js
> +        let datePartsA = elementA[timeStampAttribute].split("T")[0];
Naming suggestion datePartsX => unparsedDateX

2017-03-02 08:06 UTC, friedow approved these changes

2017-03-02 08:08 UTC, merged