BP 499 edit event query view
bptlab/argos-frontend pull request #123
Opened 2017-05-23 11:47 UTC by tommartensen

2017-05-23 13:10 UTC, MaximilianV requested changes
First comments before tryout.

2017-05-23 13:10 UTC, MaximilianV commented on src/CreateEventQueryView/CreateEventQueryView.js
> +	componentWillMount() {
Please move this function above the custom render methods.

2017-05-23 13:10 UTC, MaximilianV commented on src/index.js
> +				<Route exact path="/settings/eventType/:eventTypeId/eventQuery/:eventQueryId/:isNewQuery/edit" component={CreateEventQueryView}/>
We should consider using an understandable routing. `[...]/eventQuery/false/create` or `[...]/eventQuery/true/create` is not intuitive.
Why do we have to use `:isNewQuery` at all? In the _constructor_ you could check whether `:eventQueryId` is defined or not, couldn't you?

2017-05-23 13:10 UTC, MaximilianV commented on src/Utils/RestRoutesManager.js
> +    .set(/^eventquery\/(-?\d+)\/edit$/i, {
Please check indentation in this two new regex definitions.

2017-05-23 13:10 UTC, MaximilianV commented on src/Utils/MockData/BackendMock.js
> +        return Query.find((eventQuery) => {
Indentation.

2017-05-23 13:10 UTC, MaximilianV commented on src/SettingsView/EventTypeCard.js
> +									href={`settings/eventType/${this.props.eventType.Id}/eventQuery/true/create`}>
As stated in `index.js`, this is not that nice.

2017-05-23 13:10 UTC, MaximilianV commented on src/SettingsView/EventQueryListItem.js
> +				<IconButton href={`/settings/eventType/99101991/eventQuery/${this.props.query.Id}/false/edit`}>
Hardcoded ET-Id?

2017-05-23 13:48 UTC, MaximilianV requested changes

2017-05-23 13:48 UTC, MaximilianV commented on src/CreateEventQueryView/EventQueryInputArea.js
> +					floatingLabelText={config.descriptions.queryInputFieldHint + this.getNotEditablePartOfEventQuery()}
In _real_ create view, this results in `Esper EPL Queryundefined` as floatingLabel.

2017-05-23 13:57 UTC, MaximilianV requested changes

2017-05-23 13:57 UTC, MaximilianV commented on src/CreateEventQueryView/CreateEventQueryView.js
> +	renderCreateEventQuery() {
In `renderCreateEventQuery` and `renderEditEventQuery` there is way too much code duplication.
A parameterized function or splitting it into more, smaller functions might do the trick.

2017-05-23 14:17 UTC, MaximilianV requested changes

2017-05-23 14:17 UTC, MaximilianV commented on src/Utils/RestRoutesManager.js
>          isCachable: false
Please check indentation again.

2017-05-23 15:00 UTC, tommartensen commented on src/CreateEventQueryView/EventQueryInputArea.js
> +					floatingLabelText={config.descriptions.queryInputFieldHint + this.getNotEditablePartOfEventQuery()}
fixed

2017-05-23 15:03 UTC, tommartensen commented on src/SettingsView/EventQueryListItem.js
> +				<IconButton href={`/settings/eventType/99101991/eventQuery/${this.props.query.Id}/false/edit`}>
I thought no one would see this 🤣

2017-05-27 19:43 UTC, MaximilianV approved these changes

2017-05-28 09:11 UTC, merged