WIP: Edit Entity Mapping View
bptlab/argos-frontend pull request #127
Opened 2017-05-24 13:39 UTC by tommartensen

Yet to be tested with real backend.

2017-05-24 13:41 UTC, hpibptlab commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +		let mappings = [];
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "mappings" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-05-24 13:41 UTC, hpibptlab commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	renderEditView() {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Function has a complexity of 11 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AFunctionComplexity)

2017-05-24 13:41 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-29 08:52 UTC, MaximilianV requested changes

2017-05-29 08:52 UTC, MaximilianV commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +				selectedEventTypeId: {value: null, errorMessage: config.messages.requiredFieldMessage}
`selectedEventTypeId` seems to be an object and not an int? Maybe the naming is not appropriate.

2017-05-29 08:52 UTC, MaximilianV commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	renderComponentBody(initialData, optionalActions, submitCallback) {
Can we split this _very_ long further?

2017-05-29 09:11 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +				selectedEventTypeId: {value: null, errorMessage: config.messages.requiredFieldMessage}
The required change was addressed.

2017-05-29 12:30 UTC, julianweise submitted a review, later dismissed

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +		this.isCreateView = typeof this.props.match.params.entityMappingId === 'undefined';
This is not very nice.
Why not using props?

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +				selectedEntityTypeId: {value: null, errorMessage: config.messages.requiredFieldMessage}
You removed the id from the name before. Are you sure that "id" is the suitable solution here?

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +				floatingLabelText="Select Event Type Attribute"
Please export text to config

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +					this.handleEntityTypeAttributeChange(key, value);
Binding would be more beautiful

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	entityMappingPending() {
is never called

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	entityMappingPending() {
naming is not very good => why pending? isn´t it used to load data into the view?
A name like loadDataIntoEditView or something like that would be sufficient.

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	static renderAttributeFields(initialData) {
Implementing a static method for only accessing a member variable is useless

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +			return false;
I am not sure you should return false here. 
connectionIncomplete calls the render method of ConnectionComponent (via super) and returns either a Loading animation or a ErrorMessage if the loading procedure has not finished yet.

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +			<div ref={() => {this.oldValuesShouldBeLoaded = true;}}>
You should use the PromiseState responses (e.g.: fulfilled/rejected/pending) to decided whether fetched-data-dependent-UI has been rendered.

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +					{this.renderComponentBody(initialData, optionalActions, this.submitUpdatedMapping)}
ComponentBody: Insufficient naming
Component refers to entities of react framework ...

2017-05-29 12:30 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +			const entityMapping = this.props.entityMapping.value;
Why don´t you check for PromiseState?

2017-05-29 12:47 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +		this.isCreateView = typeof this.props.match.params.entityMappingId === 'undefined';
We cannot use props, as the view is accessed via url from the settings view and cannot be passed properties. We also can't pass this from the settings view, as we cannot read the entityMappingId from the URL when rendering a component in a route.

2017-05-29 12:47 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +		this.isCreateView = typeof this.props.match.params.entityMappingId === 'undefined';
However, I will add an explaining comment.

2017-05-29 12:49 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +				selectedEntityTypeId: {value: null, errorMessage: config.messages.requiredFieldMessage}
True that, forgot the remove it here.

2017-05-29 12:49 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	entityMappingPending() {
was removed

2017-05-29 12:52 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +					{this.renderComponentBody(initialData, optionalActions, this.submitUpdatedMapping)}
--> renderMappingForm

2017-05-29 12:54 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +				floatingLabelText="Select Event Type Attribute"
if @frederike-ramin does it as well....

2017-05-29 13:07 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	static renderAttributeFields(initialData) {
done

2017-05-29 13:11 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +					this.handleEntityTypeAttributeChange(key, value);
As discussed: binding is equally bad

2017-05-29 13:13 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +			const entityMapping = this.props.entityMapping.value;
yes, that might be better

2017-05-29 13:50 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +			return false;
the render of the fetching method is returned

2017-05-29 13:50 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +			<div ref={() => {this.oldValuesShouldBeLoaded = true;}}>
done

2017-05-30 06:52 UTC, hpibptlab commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +		if (!this.isCreateView && !this.oldValuesWereLoaded && this.oldValuesShouldBeLoaded) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Merge this if statement with the nested one. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3ACollapsibleIfStatements)

2017-05-30 06:52 UTC, hpibptlab commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +		let mappings = [];
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "mappings" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-05-30 06:52 UTC, tommartensen commented on src/CreateEntityMappingView/CreateEntityMappingView.js
> +	renderComponentBody(initialData, optionalActions, submitCallback) {
This _very_ long method was split.

2017-05-30 10:59 UTC, MaximilianV approved these changes

2017-05-30 11:00 UTC, merged