BP-462: Uniform styling EventType-/EventQuery-/Mapping-CreationView
bptlab/argos-frontend pull request #149
Opened 2017-06-01 10:24 UTC by julianweise

2017-06-01 11:03 UTC, frederike-ramin requested changes

2017-06-01 11:03 UTC, frederike-ramin commented on src/CreateEventQueryView/CreateEventQueryView.js
> +									<RaisedButton
I'd really prefer the buttons to be in the center of the whole page.

2017-06-01 11:03 UTC, frederike-ramin commented on src/CreateEventQueryView/EventQueryInputArea.js
> +					rows={5}
Maybe reduce that to 3 or something? The Area is really huge.

2017-06-01 11:03 UTC, frederike-ramin commented on src/CreateEntityMappingView/CreateEntityMappingView.js
>  					{CreateEntityMappingView.renderButtons(submitCallback)}
The buttons are not centered are they? Seems like the submit button is too far on the right.

2017-06-01 11:03 UTC, frederike-ramin commented on src/AppStyles.js
> +	textLabel: {
That's some kind of error label right?

2017-06-01 11:03 UTC, frederike-ramin commented on src/CreateEventQueryView/EventTypeInformation.js
> +import FilterList from 'material-ui/svg-icons/device/widgets';
Maybe rename this to FilterListIcon. This name is pretty confusing.

2017-06-01 11:23 UTC, julianweise commented on src/CreateEventQueryView/CreateEventQueryView.js
> +									<RaisedButton
rejected

2017-06-01 11:36 UTC, julianweise commented on src/CreateEntityMappingView/CreateEntityMappingView.js
>  					{CreateEntityMappingView.renderButtons(submitCallback)}
rejected

2017-06-02 06:51 UTC, frederike-ramin commented on src/CreateEntityMappingView/CreateEntityMappingView.js
>  					{CreateEntityMappingView.renderButtons(submitCallback)}
No. They are not.

2017-06-02 07:25 UTC, frederike-ramin approved these changes

2017-06-02 07:51 UTC, merged