Attribute Distribution Diagram
bptlab/argos-frontend pull request #171
Opened 2017-07-07 11:37 UTC by tommartensen

2017-07-07 11:39 UTC, hpibptlab commented on src/Utils/Utils.js
> +		let distribution = {};
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "distribution" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-07-07 11:39 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-07-10 09:12 UTC, frederike-ramin requested changes

2017-07-10 09:12 UTC, frederike-ramin commented on src/AnalyticsView/AnalyticsView.js
> +					<CardTitle title={"Attribute Distribution for " + attributeName}/>
Put that into config please.

2017-07-10 09:12 UTC, frederike-ramin commented on src/AnalyticsView/AnalyticsView.js
> +					diagrams.push(<div>The requested diagram cannot be displayed due to lack of data.</div>);
config please.

2017-07-10 09:12 UTC, frederike-ramin commented on src/AnalyticsView/AnalyticsView.js
> +				<Header title={"Analytics"}/>
Cooonfig^^

2017-07-10 09:12 UTC, frederike-ramin commented on src/AnalyticsView/AnalyticsView.js
> +					<Row>
Is the row really necessary?

2017-07-10 09:12 UTC, frederike-ramin commented on src/DetailView/AttributeDistributionDiagram.js
> +	static getDiagramLayout() {
Show only integer pls

2017-07-10 09:12 UTC, frederike-ramin commented on src/DetailView/AttributeDistributionDiagram.js
> +			'attributeDistributionDiagram',
that is the diagramId, right? just use that variable^^

2017-07-10 09:12 UTC, frederike-ramin commented on src/DetailView/EventTable.js
> +									<InsertChartButton style={{height: "16px", width: "16px"}}/>
Why "Insert" chart button?

2017-07-10 09:14 UTC, tommartensen commented on src/DetailView/EventTable.js
> +									<InsertChartButton style={{height: "16px", width: "16px"}}/>
I cannot do anything about the naming of [this icon](https://material.io/icons/#ic_insert_chart) in Material UI ;)

2017-07-10 09:16 UTC, tommartensen commented on src/AnalyticsView/AnalyticsView.js
> +					<Row>
nope

2017-07-10 09:19 UTC, tommartensen commented on src/DetailView/AttributeDistributionDiagram.js
> +	static getDiagramLayout() {
Should be percentage anyway

2017-07-10 10:00 UTC, frederike-ramin approved these changes

2017-07-10 10:00 UTC, merged