BP-317 Create ui for event types
bptlab/argos-frontend pull request #18
Opened 2017-03-28 14:22 UTC by julianweise

Implemented an interface to display all available eventTypes. Furthermore it is possible to delete EventTypes now.

2017-03-28 14:24 UTC, hpibptlab commented on src/DashboardView/Settings/Settings.js
> +        $('#settings-modal').on('hidden.bs.modal', function (event) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "event". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-03-28 14:24 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-03-28 15:44 UTC, friedow requested changes

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Header/Header.scss
> +		color: white;
Please use a variable here.

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +        if(this.state.error.errorCode) {
Could you extract this (until line 88) into a separate method please?

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                        <i className="fa fa-trash" onClick={this.delteEventType.bind(this, eventType)} />
Please extract the binding and do it before the HTML block. (Move it between line 77-78)

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                        <th className="center">{argosConfig.tableHeaderDescriptionDelete}</th>
Please break the content to another line.

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                    {lineElements}
Indentation missing here.

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                    <tr>
Indentation missing here.

2017-03-28 15:44 UTC, friedow commented on src/DashboardView/Settings/Settings.scss
> +  color: $COLOR-font-dark !important;
Is !important really necessary here? Can't you just use a class selector or anything more specific?

2017-03-28 15:44 UTC, friedow commented on src/RemoteHandler/DataTransmitter.js
> +        return "/api/eventtypes/delete/{0}";
Is the leading slash intended?

2017-03-28 15:44 UTC, friedow commented on src/RemoteHandler/RESTInterface.js
> +                    callbackContainer.clientErrorCallback(this.client.responseText, 403);
Please use this.client.status instead of submitting a magical number here.

2017-03-28 15:44 UTC, friedow commented on src/RemoteHandler/RESTInterface.js
> +                    callbackContainer.clientErrorCallback(this.client.responseText, 500);
Please use this.client.status instead of submitting a magical number here.

2017-03-28 15:44 UTC, friedow commented on src/__tests__/DashboardView/EventTypes.js
> +    expect(tree).toMatchSnapshot();
You should probably write unit tests for these functions too.

2017-03-30 06:14 UTC, julianweise commented on src/DashboardView/Header/Header.scss
> +		color: white;
fixed using $COLOR-font-light from definitions.scss

2017-03-30 06:20 UTC, julianweise commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +        if(this.state.error.errorCode) {
done

2017-03-30 06:33 UTC, julianweise commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                        <i className="fa fa-trash" onClick={this.delteEventType.bind(this, eventType)} />
fixed

2017-03-30 06:34 UTC, julianweise commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                    <tr>
fixed

2017-03-30 06:34 UTC, julianweise commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                        <th className="center">{argosConfig.tableHeaderDescriptionDelete}</th>
fixed

2017-03-30 06:35 UTC, julianweise commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +                    {lineElements}
fixed

2017-03-30 06:35 UTC, julianweise commented on src/RemoteHandler/DataTransmitter.js
> +        return "/api/eventtypes/delete/{0}";
No, it is not - Good point!
Fixed

2017-03-30 06:39 UTC, julianweise commented on src/RemoteHandler/RESTInterface.js
> +                    callbackContainer.clientErrorCallback(this.client.responseText, 403);
Done and refactored case 403 and 500 to be one common case.

2017-03-30 06:39 UTC, julianweise commented on src/RemoteHandler/RESTInterface.js
> +                    callbackContainer.clientErrorCallback(this.client.responseText, 500);
fixed, see comment above

2017-03-30 06:49 UTC, julianweise commented on src/__tests__/DashboardView/EventTypes.js
> +    expect(tree).toMatchSnapshot();
Fixed

2017-03-30 06:58 UTC, julianweise commented on src/DashboardView/Settings/Settings.scss
> +  color: $COLOR-font-dark !important;
I am afraid this is not possible. We have to use !important; here.

2017-03-30 07:29 UTC, friedow approved these changes

2017-03-30 07:34 UTC, merged