Display esper query validation messages.
bptlab/argos-frontend pull request #19
Opened 2017-03-30 08:23 UTC by friedow

2017-03-30 09:34 UTC, julianweise requested changes

2017-03-30 09:34 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
>              eventQuery: '',
Please do not add eventQuery to state. This makes no sense in this case but causes unnecessary rerenderings.
Better add it to this.

2017-03-30 09:34 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        const modalIsAbleToSave = this.isModalAbleToSave(name, this.state.eventQuery);
Renaming isModalAbleToSave -> queryIsSafeable makes sense here. Our main target is the eventType (and its query of course). Modal ist only an UI helper which should not be reflected in namings.

2017-03-30 09:34 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        this.eventQueryFormValidation(queryValue);
Does nearly the same stuff like isModalAbleToSave(). Plese consider building one function for both operations.

2017-03-30 09:34 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
>          const eventType = this.buildJSONSerializableDataContainer();
This stuff should be done on DataTransmitter, because it relates to network stuff. This does not have anything to do with queries.

2017-03-30 09:34 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +                        {this.state.validationClasses && <div className="form-control-feedback">This field can't be empty.</div>}
Please use config for hard coded strings.

2017-03-30 09:34 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterfaceAttributeList/QueryInterfaceAttributeList.js
> +                    {this.state.validationClasses && <div className="form-control-feedback">This field can't be empty.</div>}
This validation stuff occures the second time here. Please think about outsourcing it to a new component.

2017-03-30 09:34 UTC, julianweise commented on src/Utils/Modal/Modal.js
> +                            <button type="button" className="btn btn-primary" onClick={this.onSubmit} disabled={!this.props.isAbleToSave && `disabled`}>
Line too long

2017-03-30 09:34 UTC, julianweise commented on src/__tests__/ProductView/QueryInterface.js
Branch coverage is not 100%. Please try to achieve 100%.

2017-03-30 13:21 UTC, friedow commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        this.eventQueryFormValidation(queryValue);
Could you specify this more please?

2017-03-30 17:38 UTC, friedow commented on src/__tests__/ProductView/QueryInterface.js
Easier said than done. Do you know how I can get the uncovered lines for branch coverage?

2017-04-01 09:01 UTC, julianweise commented on src/__tests__/ProductView/QueryInterface.js
I think there is no other solution than figuring out each execution branch.
I did not find any coveralls option displaying it.

2017-04-01 09:02 UTC, julianweise commented on src/__tests__/ProductView/QueryInterface.js
>  test('Handling save query failure', () => {
Seems to be wrong test description?

2017-04-01 09:04 UTC, julianweise approved these changes
Two small comments but the changes seem to be okay.
Maybe you can solve the branch coverage problem but do not invest to much time.

2017-04-03 06:28 UTC, merged