Code Review
bptlab/argos-frontend pull request #190
Opened 2017-07-17 12:15 UTC by tommartensen

2017-07-17 12:58 UTC, frederike-ramin requested changes

2017-07-17 12:58 UTC, frederike-ramin commented on src/App.css
> +.rotate90 {
This class is doubled. (see above)

2017-07-17 12:58 UTC, frederike-ramin commented on src/DetailView/DetailView.js
> +import AppStyles from "../AppStyles";
Why do you need AppStyles here but not aphrodite?

2017-07-17 12:58 UTC, frederike-ramin commented on src/Header.js
> +			appBarStyle = "headerBorderDetail positionFixedTop" + css(statusColor.color);
Color is wrog and header not sticky anymore.

2017-07-18 07:53 UTC, tommartensen commented on src/App.css
> +.rotate90 {
thx

2017-07-18 07:56 UTC, tommartensen commented on src/DetailView/DetailView.js
> +import AppStyles from "../AppStyles";
to style the switch color

2017-07-18 08:10 UTC, frederike-ramin approved these changes

2017-07-18 08:16 UTC, merged