Delete button for filters
bptlab/argos-frontend pull request #21
Opened 2017-03-30 14:33 UTC by frederike-ramin

1) Rename Inputfield zo RemovableIputField
2) Add delete button to filters on detail page (same behavior as deleting the input field's value)

2017-03-30 14:35 UTC, hpibptlab commented on src/Utils/RemovableInputField.js
> +    handleRemove(event) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "event". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-03-30 14:35 UTC, hpibptlab commented on src/ProductView/FilterBar/FilterBar.js
> +        if(this.props.filter[this.props.filter.length - 1] === currentFilter) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this if-then-else statement by a single return statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS1126)

2017-03-30 14:35 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-03-30 18:35 UTC, friedow requested changes

2017-03-30 18:35 UTC, friedow commented on src/App/App.scss
> +    border-style: none none solid none;
If I click the delete button, there is a border / shadow appearing for a short time. This should not happen, therefore please check the button for :hover / :focus / :active css attributes.

2017-03-30 18:35 UTC, friedow commented on src/Utils/RemovableInputField.js
> +class RemovableInputField extends Component {
Why have you renamed the component?

2017-03-30 18:35 UTC, friedow commented on src/ProductView/FilterBar/FilterBar.js
> +                                             onInputChange={this.props.onInputChange} showRemove={this.decideOnRemoveButton(filter)}/>
Please rename "showRemove" to "displayRemoveButton" for a better understanding.

2017-03-30 18:35 UTC, friedow commented on src/ProductView/FilterBar/FilterBar.js
> +                        <RemovableInputField key={filter.id} id={filter.id} value={filter.value} placeholder="Search..."
Please break this component initialisation after each parameter.
Corresponding convention: If a component initialisation has more than 2 parameters, insert a line break after each parameter.
(I'll add the development conventions to the readme.)

2017-03-30 18:35 UTC, friedow commented on src/Utils/RemovableInputField.js
> +            return <button className="input-group-addon" id="remove-addon" onClick={this.handleRemove}>
Please correct the indentation and wrap the jsx in round brackets. (For a template just look on the render method.)

2017-03-31 08:20 UTC, frederike-ramin commented on src/Utils/RemovableInputField.js
> +class RemovableInputField extends Component {
It is a lot more descriptive name. Not every input field should be removable. that's the speciality about this input field. That's why a new name.

2017-03-31 08:34 UTC, frederike-ramin commented on src/App/App.scss
> +    border-style: none none solid none;
Does the new :outline attribute fix that for you?

2017-03-31 09:16 UTC, friedow commented on src/App/App.scss
> +    border-style: none none solid none;
Yep you fixed it, thanks.

2017-03-31 09:16 UTC, friedow commented on src/Utils/RemovableInputField.js
> +class RemovableInputField extends Component {
You're right.

2017-03-31 09:16 UTC, friedow approved these changes

2017-03-31 09:17 UTC, merged