BP-320: Display predictions in chart
bptlab/argos-frontend pull request #25
Opened 2017-04-03 14:52 UTC by julianweise

Implemented bar chart (used CharJS) to display all causes and their probability of a specific errorType.
All errorTypes are displayed within a product as list. Clicking on an list element opens a new view (modal) to display the bar chart.
Attention: You have to select a configuration to view the list of errorTypes!

2017-04-03 14:53 UTC, hpibptlab commented on src/__tests__/ProductView/PredictionList.js
> +    let tree = component.toJSON();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "tree" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-04-03 14:53 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-03 15:02 UTC, tommartensen commented on src/__tests__/testData/frontend_configurations.js
> +                causeDescription: "Kabelbaum missing",
Please translate this into english!

2017-04-03 15:02 UTC, tommartensen commented on src/__tests__/testData/frontend_configurations.js
> +                causeDescription: "Kabelbaum missing",
Please translate this into english!

2017-04-03 15:02 UTC, tommartensen commented on src/__tests__/testData/frontend_configurations.js
> +                causeDescription: "Kabelbaum missing",
Please translate this into english!

2017-04-04 08:11 UTC, friedow requested changes

2017-04-04 08:11 UTC, friedow commented on src/ProductView/Header/Header.js
>                                  <ConfigurationHeader configurations={this.props.configurations} onChangeProductConfiguration={this.props.onChangeProductConfiguration}/>
Line too long.

2017-04-04 08:11 UTC, friedow commented on src/ProductView/PredictionList/PredictionList.js
> +    constructor(props) {
Remove unnecessary constructor.

2017-04-04 08:11 UTC, friedow commented on src/ProductView/PredictionList/PredictionList.js
> +        const errorList = [];
Please extract the preparation of errorList into a own method.

2017-04-04 08:11 UTC, friedow commented on src/ProductView/PredictionList/PredictionList.scss
> +  margin-top: 2vw;
Is using vw safe here?

2017-04-04 08:11 UTC, friedow commented on src/ProductView/PredictionList/PredictionList.scss
> +  width: 100%;
please use a w-100 css class onto the html element instead of using width: 100% here.
Reference: https://v4-alpha.getbootstrap.com/utilities/sizing/

2017-04-04 08:11 UTC, friedow commented on src/ProductView/PredictionList/PredictionView/PredictionView.js
> +        const modalId = "#prediction-view-"+this.props.errorType.errorTypeId+"-modal";
You should extract the id selector into a const variable.

2017-04-04 08:11 UTC, friedow commented on src/ProductView/ProductView.js
> +                                    configuration={this.state.configuration} />
Don't break that.

2017-04-04 08:11 UTC, friedow commented on src/__tests__/ProductView/PredictionList.js
> +            configuration={testConfigurations.CONFIGURATIONS[0]} />);
Don't break that.

2017-04-04 12:44 UTC, julianweise commented on src/ProductView/PredictionList/PredictionList.js
> +    constructor(props) {
solved

2017-04-04 12:44 UTC, julianweise commented on src/ProductView/Header/Header.js
>                                  <ConfigurationHeader configurations={this.props.configurations} onChangeProductConfiguration={this.props.onChangeProductConfiguration}/>
fixed

2017-04-04 12:47 UTC, julianweise commented on src/ProductView/PredictionList/PredictionList.js
> +        const errorList = [];
done

2017-04-04 12:48 UTC, julianweise commented on src/ProductView/PredictionList/PredictionList.scss
> +  margin-top: 2vw;
Changed it to px.

2017-04-04 13:13 UTC, julianweise commented on src/ProductView/PredictionList/PredictionList.scss
> +  width: 100%;
fixed

2017-04-04 13:15 UTC, julianweise commented on src/ProductView/ProductView.js
> +                                    configuration={this.state.configuration} />
outdated, now has to props.

2017-04-04 13:15 UTC, julianweise commented on src/__tests__/ProductView/PredictionList.js
> +            configuration={testConfigurations.CONFIGURATIONS[0]} />);
see comment above.

2017-04-04 13:18 UTC, julianweise commented on src/ProductView/PredictionList/PredictionView/PredictionView.js
> +        const modalId = "#prediction-view-"+this.props.errorType.errorTypeId+"-modal";
fixed

2017-04-04 13:36 UTC, friedow approved these changes

2017-04-04 13:36 UTC, merged