Bp 359 Query interface - notification for successfully saving event type
bptlab/argos-frontend pull request #28
Opened 2017-04-04 11:59 UTC by friedow

2017-04-04 12:00 UTC, hpibptlab commented on src/Notification/Notification.js
> +    componentWillReceiveProps(nextProps) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "nextProps". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-04-04 12:00 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-04-04 15:07 UTC, tommartensen requested changes
Please fix the two typos and see the other comment I will write directly into the PR

2017-04-04 15:07 UTC, tommartensen commented on src/__tests__/ProductView/QueryInterface.js
> +test('Handling save query sucess', () => {
sucess -> success

2017-04-04 15:07 UTC, tommartensen commented on src/__tests__/ProductView/__snapshots__/QueryInterface.js.snap
> +exports[`test Handling save query sucess 1`] = `
sucess -> success

2017-04-04 15:08 UTC, tommartensen commented
@friedow: The implementation just works once on every page. 
If I saved an event type, the notification slides in. If I re-open the query interface and save a new event type, the notification does not appear again (neither an error).

2017-04-10 09:56 UTC, tommartensen approved these changes

2017-04-10 10:41 UTC, merged