BP 359: Implementation of Confirmation
bptlab/argos-frontend pull request #29
Opened 2017-04-05 08:00 UTC by tommartensen

For the confirmation of the deletion of an event type a new generic modal was built and may be used by any component that does not want to use the Window.confirm()-method.

2017-04-06 09:50 UTC, friedow requested changes

2017-04-06 09:50 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +        $("#delete-prompt-modal").modal('toggle');
Please use `.modal('show');` here, since it is more explicit.

2017-04-06 09:50 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +        $("#delete-prompt-modal").modal('toggle');
Please use `.modal('hide');` here, since it is more explicit.

2017-04-06 09:50 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +    deleteEventType(eventType) {
Please rename this method to `handleDeleteEventType`, because it's the base method of a callback.

2017-04-06 09:50 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +    onAbort() {
Please rename this method to `handleAbortDeleteEventType` or `handleAbortDelete`, because it's the base method of a callback.

2017-04-06 09:50 UTC, friedow commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +            const deleteCallback = this.deleteEventType.bind(this, eventType);
Please rename this to `onDelete` for consistency reasons.

2017-04-06 09:50 UTC, friedow commented on src/__tests__/Utils/ConfirmOverlay.js
> +    const callbackMock = jest.fn();
Please extract this to a `beforeEach()` method. Reference: `__tests__/ProductView/QueryInterface.js`

2017-04-06 12:55 UTC, tommartensen commented on src/DashboardView/Settings/EventTypes/EventTypes.js
> +            const deleteCallback = this.deleteEventType.bind(this, eventType);
I will rename both to ...Callback

2017-04-10 12:00 UTC, friedow approved these changes

2017-04-10 12:07 UTC, merged