[WIP] Bp 397 rest routes
bptlab/argos-frontend pull request #44
Opened 2017-04-25 14:01 UTC by MaximilianV

Work in progress: Please do not merge :)
Contains some improvements and refactorings

2017-04-27 12:42 UTC, hpibptlab commented on src/Utils/ConnectionComponent.js
> +			console.log(promise);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS2228)

2017-04-27 12:42 UTC, hpibptlab commented on src/Utils/MockData/BackendMock.js
> +	static getEntityTypeAttributes(params) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "params". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-04-27 12:42 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 2 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-05-02 09:30 UTC, friedow requested changes

2017-05-02 09:30 UTC, friedow commented on src/GridView/CardGrid.js
> +							<CardTitle title={childEntity.Name} subtitle={this.props.entityType.name}/>
Break this line.

2017-05-02 09:30 UTC, friedow commented on src/GridView/CardGrid.js
> +						<Card className="card" key={index}>
Break this line.

2017-05-02 09:30 UTC, friedow commented on src/GridView/CardGrid.js
> +								<FlatButton label="Children" className="card-button" href={`./${childEntity.Id}`}/>
Break this line.

2017-05-02 09:30 UTC, friedow commented on src/GridView/CardGrid.js
> +								<FlatButton label="Inspect" className="card-button" href={`/details/${childEntity.Id}`}/>
Break this line.

2017-05-02 09:30 UTC, friedow commented on src/GridView/CardGrid.js
> +								<FlatButton label="Children" className="card-button" href={`./${childEntity.Id}`}/>
This link is probably wrong. it should be /grid/${childEntity.Id}

2017-05-02 09:30 UTC, friedow commented on src/GridView/GridView.js
> +		let { hierarchy, entity } = this.props;
I would prefer an explicit assignment.

2017-05-02 09:30 UTC, friedow commented on src/GridView/GridView.js
> +		let { hierarchy, entity } = this.props;
Can you extract Line 22 - 26 into a method?

2017-05-02 09:30 UTC, friedow commented on src/Utils/ErrorMessage.js
> +				<p>{this.props.message}</p>
Now this way again? (Merge failure?)

2017-05-02 09:30 UTC, friedow commented on src/Utils/MockData/BackendMock.js
> +import Hierarchy from './Transport for London/Hierarchy.js';
We should really avoid directory and filenames with whitespaces.

2017-05-02 09:30 UTC, friedow commented on src/Utils/MockData/BackendMock.js
> +		const targetRoute = [...RouteMapper.keys()].find((route) => {
What does `...` do?

2017-05-02 09:30 UTC, friedow commented on src/Utils/MockData/BackendMock.js
> +			return (Entity.ParentId === parseInt(params[1], 10) && Entity.TypeId === parseInt(params[2], 10));
Thats a long line.

2017-05-02 09:30 UTC, friedow commented on src/index.js
> +			<Route exact path="/" render={() => {
Please merge carefully. Tom solved this too...

2017-05-02 09:33 UTC, MaximilianV commented on src/Utils/MockData/BackendMock.js
> +		const targetRoute = [...RouteMapper.keys()].find((route) => {
`.keys()` gives you an iterator for _RouteMapper_. But `find()` expects an array. The `...` operator _converts_ the iterator to an array we can operate on.

2017-05-02 09:34 UTC, MaximilianV commented on src/Utils/ErrorMessage.js
> +				<p>{this.props.message}</p>
Yes we could avoid the `dangerouslySetInnerHTML` 😄

2017-05-02 09:43 UTC, MaximilianV commented on src/index.js
> +			<Route exact path="/" render={() => {
`Tom` approves this routing 👍

2017-05-02 09:49 UTC, friedow approved these changes

2017-05-02 09:49 UTC, merged