Bp 479 logic for create event type
bptlab/argos-frontend pull request #76
Opened 2017-05-09 13:35 UTC by julianweise

2017-05-09 13:37 UTC, hpibptlab commented on src/CreateEventTypeView/CreateEventTypeView.js
> +export default ConnectionComponent.argosConnector()(props => ({
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove the unused function parameter "props". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

2017-05-09 13:37 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-05-09 14:30 UTC, MaximilianV requested changes

2017-05-09 14:30 UTC, MaximilianV commented on src/CreateEventTypeView/CreateEventTypeView.js
> +			errorState['eventTypeNameErrorText'] = 'Please fill out this field';
Maybe we extract it into a config variable, like _formFieldRequired: Please fill out ..._?

2017-05-09 14:30 UTC, MaximilianV commented on src/CreateEventTypeView/CreateEventTypeView.js
> +		deleteQueryResponse: {
How does `deleteQueryResponse` fits to `createEventType`?

2017-05-09 14:30 UTC, MaximilianV commented on src/CreateEventTypeView/CreateEventTypeView.js
> +		if(event.target.value) {
Prevents the deletion of last character:

1. Type something in input field
1. Try to delete everything by pressing `back` multiple times, or marking all and then `back`
1. You will see that at least the last character is quite rebellious

This is slightly inconvenient for the user.

2017-05-09 14:30 UTC, MaximilianV commented on src/CreateEventTypeView/CreateEventTypeView.js
> +		if(event.target.value) {
Same as in `handleChangeEventTypeName`.

2017-05-11 07:19 UTC, MaximilianV approved these changes

2017-05-11 08:00 UTC, merged