BP-482: Event Query saving
bptlab/argos-frontend pull request #83
Opened 2017-05-11 11:23 UTC by julianweise

2017-05-11 11:37 UTC, frederike-ramin requested changes

2017-05-11 11:37 UTC, frederike-ramin commented on src/CreateEventQueryView/CreateEventQueryView.js
> +	submitQuery() {
There is no target route defined in case of a "save" click.

2017-05-15 06:46 UTC, julianweise commented on src/CreateEventQueryView/CreateEventQueryView.js
> +	submitQuery() {
I do not get the point of your comment.
SubmitQuery calls _createEventQuery_ in our connector (line  127-133), which triggers a request to /eventquery/create

2017-05-15 07:06 UTC, frederike-ramin requested changes

2017-05-15 07:06 UTC, frederike-ramin commented on src/CreateEventQueryView/CreateEventQueryView.js
> +		let noValidationError = true;
To me it would be easer to understand if this was "showValidationError", so the opposite of what you did.

2017-05-15 07:06 UTC, frederike-ramin commented on src/Utils/MockData/BackendMock.js
> +	static createEventQueryType() {
create EventqueryTYPE? Why type?

2017-05-15 07:22 UTC, frederike-ramin approved these changes

2017-05-15 07:25 UTC, merged