Bp 386 add filter bar on grid page
bptlab/argos-frontend pull request #84
Opened 2017-05-11 12:39 UTC by Munin33

2017-05-11 12:42 UTC, hpibptlab commented on src/GridView/CardGrid.js
> +		console.log(attributeArray);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove this logging statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS2228)

2017-05-11 12:42 UTC, hpibptlab commented on src/GridView/CardGrid.js
> +		let attributeArray = [];
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "attributeArray" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-05-11 12:42 UTC, hpibptlab commented on src/GridView/CardGrid.js
> +		else if (this.doesContain(attributeValues, filter.value)){
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either merge this branch with the identical one on line "44" or change one of the implementations. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS1871)

2017-05-11 12:42 UTC, hpibptlab commented on src/GridView/GridView.js
> +		let filterBar = this.loadFilterBar();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "filterBar" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-05-11 12:42 UTC, hpibptlab commented
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-13 11:58 UTC, MaximilianV requested changes
Looks good to me!

2017-05-13 11:58 UTC, MaximilianV commented on src/GridView/GridView.js
> +		this.handleFilterChange = this.handleFilterChange.bind(this);
I'm not sure, but I think it is a convention to but bindings at the bottom of the constructor.

2017-05-13 11:58 UTC, MaximilianV commented on src/GridView/GridView.js
> +					{filterBar}
If you have no condition for `filterBar` you can put the function call here directly instead of using a variable.

2017-05-15 07:50 UTC, tommartensen commented on src/GridView/GridView.js
> +		this.handleFilterChange = this.handleFilterChange.bind(this);
https://medium.freecodecamp.com/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56 -> Approach #4 
1. super call
2. state definition
3. bindings

2017-05-15 09:32 UTC, frederike-ramin commented
Replaced by #92.

2017-05-15 09:32 UTC, closed without merging