BP-385 Implemented status diagram
bptlab/argos-frontend pull request #85
Opened 2017-05-11 12:59 UTC by friedow

2017-05-11 13:02 UTC, hpibptlab commented on src/GridView/StatusDiagram.js
> +		let data = [];
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "data" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-05-11 13:02 UTC, hpibptlab commented on src/GridView/StatusDiagram.js
> +		let statuses = config.statuses;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make "statuses" "const". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3353)

2017-05-11 13:02 UTC, hpibptlab commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Utils.js](https://github.com/bptlab/argos-frontend/blob/a271d96e53666865c2e40786d8b391ffe4d93f67/src/Utils/Utils.js): Rename this file to "Header". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3317)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-11 13:04 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-15 07:15 UTC, julianweise requested changes

2017-05-15 07:15 UTC, julianweise commented on src/GridView/CardGrid.js
> +			return {backgroundColor: Utils.getStatus("UNDEFINED").color};
I think it would be better to define a UNDEFINE status and return it inside the Utils.getStatus() methid

2017-05-15 07:15 UTC, julianweise commented on src/GridView/CardGrid.js
> +			return {backgroundColor: Utils.getStatus("UNDEFINED").colorLight};
Same as above

2017-05-15 07:15 UTC, julianweise commented on src/GridView/StatusDiagram.js
> +		let statuses = config.statuses;
and install SonaLint on youe dev system ... No approve before you have done it :D

2017-05-15 08:01 UTC, julianweise approved these changes

2017-05-15 08:11 UTC, merged