Implemented interface for esper query creation
bptlab/argos-frontend pull request #9
Opened 2017-02-28 15:29 UTC by friedow

2017-02-28 16:28 UTC, julianweise requested changes

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/ProductView.js
> +                        dataSender={this.props.dataSender}
Better naming suggestion: data reception

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/Modal/Modal.js
> +import React, { Component } from 'react';
Error handling + displaying is missing.

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/Modal/Modal.js
> +
Success notification is missing

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/Modal/Modal.js
> +import React, { Component } from 'react';
clientDataContainer.clientErrorCallback is not a function

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        this.setState({ eventQuery: this.props.defaultQuery });
Please do not use props for defining defaultQueries.
Transfer it to a static method and after merging it to developer transfer it to config.

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        return eventType;
Please directly return builded object from eventType

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        for (let i = 0; i < attributes.length; i++) {
Please comment on this construct.
I think it is necessary here, due to the special reuqirements of the backend (and JSON parsing) but it is 
poorly understandable.

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +    getEventType() {
Give the function a more descriptivename. e.g.: buildBackendDataContainer or buildJSONSerializableDataContainer, ...

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +        this.props.dataSender.createEventtype(this.state.eventQuery, eventType, this.handleEventTypeData, this.handleError);
line too long

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterface.js
> +                    <QueryInterfaceHeader eventTypeName={this.state.eventTypeName}
Maybe rename header to attributeList or something elese. Header indicates an protocol header or an UI header ...

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/QueryInterface/QueryInterfaceHeader/QueryInterfaceHeaderAttribute/QueryInterfaceHeaderAttribute.js
> +                        <option>STRING</option>
We should do this more generic.
e.g.: receiving information about possible data types from backend or transfering it to the central config.

2017-02-28 16:28 UTC, julianweise commented on src/ProductView/TabBar/TabBar.js
> +                            defaultQuery="INSERT INTO TestErrorEvents SELECT timestamp, productId, productFamilyId FROM FeedbackData"/>
See comment above about default query / values in source code.

2017-02-28 16:28 UTC, julianweise commented on src/RemoteHandler/DataTransmitter.js
> +        this.client.sendRequest(this.receiveResults, this.receiveError, callbackContainer, JSON.stringify(data));
Line is too long

2017-02-28 16:28 UTC, julianweise commented on src/RemoteHandler/DataTransmitter.js
> +        this.client.sendRequest(this.receiveResults, this.receiveError, callbackContainer, JSON.stringify(data));
I would suggest to create a new function for JSON parsing to catch parsing errors and displaying them sufficiently.

2017-02-28 16:28 UTC, julianweise commented on src/RemoteHandler/RESTInterface.js
> +        this.client.send(data);
Please check sending of null concerning any possible error case.

2017-02-28 16:28 UTC, julianweise commented on src/index.js
> +const dataSender = new DataTransmitter(API_SERVER_URL, API_SERVER_PORT);
See my comment above concerning naming.

2017-03-22 17:48 UTC, friedow commented on src/ProductView/ProductView.js
> +                        dataSender={this.props.dataSender}
I think this name doesn't fit to well.

2017-03-23 07:50 UTC, julianweise commented on src/ProductView/ProductView.js
> +                        dataSender={this.props.dataSender}
yes, fair

2017-03-23 07:51 UTC, julianweise commented
What´s about this pull request? It belongs to our last sprint and is still not solved.

2017-03-23 10:33 UTC, friedow commented on src/RemoteHandler/DataTransmitter.js
> +        this.client.sendRequest(this.receiveResults, this.receiveError, callbackContainer, JSON.stringify(data));
I wouldn't change that, if thats okay with you.

2017-03-23 11:05 UTC, friedow commented on src/ProductView/TabBar/QueryInterface/Modal/Modal.js
> +import React, { Component } from 'react';
Done that.

2017-03-23 11:05 UTC, friedow commented on src/ProductView/TabBar/QueryInterface/Modal/Modal.js
> +
Done that too.

2017-03-23 11:06 UTC, friedow commented on src/RemoteHandler/DataTransmitter.js
> +        this.client.sendRequest(this.receiveResults, this.receiveError, callbackContainer, JSON.stringify(data));
Done.

2017-03-23 11:06 UTC, friedow commented on src/RemoteHandler/DataTransmitter.js
> +        this.client.sendRequest(this.receiveResults, this.receiveError, callbackContainer, JSON.stringify(data));
Done

2017-03-23 11:47 UTC, friedow commented on src/index.js
> +const dataSender = new DataTransmitter(API_SERVER_URL, API_SERVER_PORT);
Done

2017-03-23 12:33 UTC, julianweise commented
Please ensure that name and event query is not empty before requesting backend.

2017-03-24 12:03 UTC, merged